### ISSUE TITLE
class.initialize conflicts with class access expressions proposal

### ISSUE THREAD

**Issue by rbuckton** [littledan/proposal-new-initialize#5]
Does this mean we would abandon https://github.com/tc39/proposal-class-access-expressions? Do we need to use `class.` for this, since we already have `new.` (i.e. use `new.initialize` instead)?

**Comment by nicolo-ribaudo** [comment]
+1 for `new`, since `initialize` is more related to the creation of a new instance rather than to the class itself.

If this proposal sticks with `class`, maybe that one could be changed to use `static`.

**Comment by littledan** [comment]
I think we can find names that accommodate both, as [I wrote in the explainer](https://github.com/littledan/proposal-class-initialize/blob/master/README.md#detailed-syntax-and-semantics), and was definitely not trying to abandon the other one. I hadn't thought of `new.initialize`--I like that one.

**Comment by jridgewell** [comment]
Can be closed now?

**Comment by littledan** [comment]
Yep, it's all switched to new.initialize.
